### ISSUE TITLE
Wont Install?

### ISSUE THREAD

**Issue by gibbo1973** [BBergle/mkv-language-remover#4]
<img width="1259" alt="Screenshot 2023-11-11 at 16 52 46" src="https://github.com/BBergle/mkv-language-remover/assets/123332824/1de40981-0d37-4377-b51e-c398191e4bbd">

**Comment by BBergle** [comment]
Dockerhub is currently having registry issues. 
I cant install any unraid docker right now
![image](https://github.com/BBergle/mkv-language-remover/assets/58752312/4b88c83a-638b-4b88-a24e-8f317fac16ab)

**Comment by gibbo1973** [comment]
Thanks for the info, will try later!

**Comment by BBergle** [comment]
No Problem!

**Comment by ktfcaptain** [comment]
> Thanks for the info, will try later!
> […](#)

edit: I'm just dumb, there is a warning in all caps.

~~Just a 'heads-up'...didn't start for me at first then I got distracted with stuff and ran it again without paying attention...
I'm not sure how much time had passed but I noticed it was running from my dashboard so opened the log and it was churning away at my movies.  I have no idea if I had settings correct or what was actually done, but I was expecting a WebUI and/or some options ffs...........~~

**Comment by BBergle** [comment]
No, there is no webUI, the logs will give you all of the output that you need.

**Comment by BBergle** [comment]
Checking means it is checking the mkv files for the given language, processing means its actually remuxing

**Comment by ktfcaptain** [comment]
> No, there is no webUI, the logs will give you all of the output that you need.

My fault, I didn't notice the warning until I just looked at it again.  

I'm guessing the "Languages:" field is for what you want to keep?  I over-think everything and wasn't sure if that's what it's looking for(to remove) or what it keeps.  Luckily (I think) I entered "eng", pressed APPLY, then moved on letting it build, so think I'm fine.

My usual practice is to install things default then check later at what isn't working so if I just left it default and didn't notice anything I'd be kicking myself all weekend lol.

Seems like a great app so I apologize for not paying enough attention.  Thank you for your work and quick response!!

**Comment by BBergle** [comment]
Its no problem.  The languages field is what you want to remove, I will update the template to clarify that. This is my first time releasing a public app so I also have a lot to learn.

**Comment by ktfcaptain** [comment]
Oh, okay.  

Would there be any way to reverse that?  I personally have no idea what all languages are in my entire library, just what I would want to keep.  It probably wouldn't be very hard for me to scan things and get a list, but I know it's a mixed bag and my preferred language isn't even always the first audio track. Just a thought, thanks again either way.

**Comment by BBergle** [comment]
I will look into a way to only keep English. The entire reason I made this was because the movies I "source" have Russian audio tracks and I just wanted to remove them while keeping all other languages. I have some foreign movies that are not Russian and English and I don't want to remove those either.

**Comment by gibbo1973** [comment]
Yes that would be a good feature to have, been able to choose a certain language only!On 11 Nov 2023, at 18:00, Benny Bergle ***@***.***> wrote:﻿
I will look into a way to only keep English. The entire reason I made this was because the movies I "source" have Russian audio tracks and I just wanted to remove them while keeping all languages. I have some foreign movies that are not Russian and English and I don't want to remove those either.
